apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: animal-rescue

resources:
  - namespace.yaml
  - animal-rescue-frontend.yaml
  - animal-rescue-backend.yaml
  - gateway-demo.yaml
  - gateway-demo-with-dynamic-routes.yaml
