spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER}.mysql.database.azure.com:3306/animals?serverTimezone=UTC&sslmode=required
    username: ${MYSQL_USERNAME}@${MYSQL_SERVER}
    password: ${MYSQL_PASSWORD}